name: Run Blocks Playwright Tests

on:
    pull_request:
        paths:
            - '.github/workflows/blocks-playwright.yml' # This file
            - 'plugins/woocommerce-blocks/**'
            - 'plugins/woocommerce/src/Blocks/**'
            - 'plugins/woocommerce/templates/**'
            - 'plugins/woocommerce/patterns/**'
    # Allow manually triggering the workflow.
    workflow_dispatch:


env:
    FORCE_COLOR: 1

jobs:
    e2e:
        name: Shard ${{ matrix.part }} of ${{ matrix.total-parts }}
        timeout-minutes: 60
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: plugins/woocommerce-blocks
        strategy:
            fail-fast: false
            matrix:
                part: [1, 2, 3, 4, 5, 6, 7, 8]
                total-parts: [8]

        steps:
            - uses: actions/checkout@v3

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo
              with:
                  install: '@woocommerce/plugin-woocommerce...'
                  build: '@woocommerce/plugin-woocommerce'

            - name: Install Playwright dependencies
              run: pnpm exec playwright install chromium --with-deps

            - name: Setup testing environment and start the server
              run: pnpm env:start

            - name: Run Playwright tests
              run: pnpm test:e2e --shard=${{ matrix.part }}/${{ matrix.total-parts }}

            - name: Archive debug artifacts (screenshots, traces)
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: failures-artifacts
                  path: plugins/woocommerce-blocks/tests/e2e/artifacts/test-results
                  if-no-files-found: ignore
